import Link from 'next/link';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <nav>
          <div>
            <Link href="/">home</Link> <Link href="/page">page</Link>{' '}
            <Link href="/cookie">cookie</Link>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
